services:
  - type: web
    name: asistente-legal-ia
    env: python
    plan: free
    pythonVersion: '3.12.8'  
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: HUGGINGFACEHUB_API_TOKEN
        fromSecret: true 
      - key: PINECONE_API_KEY
        fromSecret: true
    